#!/bin/bash

IONIC_VERSION='0.5'
NODE_VERSION='4.1.2'
RUBY_VERSION='1.0'
NGINX_VERSION='1.9'
MONGO_VERSION='0.1'

function printHelp() {
    echo "How to use: ${0} <cmd>"
    echo "Where cmd could be: "
    echo "  node    - node bash"
    echo "  ruby    - ruby bash"
    echo "  nginx   - web server on premise"
    echo "  ionic   - ionic bash"
    echo "  is      - ionic server"
    echo "  mongo   - mongo client"
}

case "$1" in
    "node")
        docker run -it --rm --name node-box   -P -v $(pwd):/app -u=petru -w /app petruisfan/node:$NODE_VERSION /bin/bash;;
    "ruby")
        docker run -it --rm --name ruby-box   -P -v $(pwd):/app -u=petru -w /app petruisfan/ruby:$RUBY_VERSION /bin/bash;;
    "nginx")
        #
        # Run a on-premise nginx app that will server the current folder
        #
        docker run     --rm --name nginx-box -p 80:80 -v $(pwd):/usr/share/nginx/html nginx:$NGINX_VERSION;;
    "ionic")
        #--net host \
        docker run -it --rm \
            --name ionic-box \
            -u=docker \
            -p 8100:8100 \
            -p 35729:35729 \
            -v $(pwd):/code \
            -v ~/.gradle:/home/docker/.gradle \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -w /code \
            -e DISPLAY=$DISPLAY \
            --privileged -v /dev/bus/usb:/dev/bus/usb \
            petruisfan/ionic:$IONIC_VERSION bash
        ;;
    "is")
        docker run -it --rm \
            --name ionic-box \
            -p 8100:8100 \
            -p 35729:35729 \
            -u=docker \
            -v $(pwd):/code \
            -w /code \
            --privileged -v /dev/bus/usb:/dev/bus/usb \
            petruisfan/ionic:$IONIC_VERSION
        ;;
    "mongo")
        docker run -it --rm \
            --name mongo-client \
            -u=petru \
            -v $(pwd):/code \
            -w /code \
            petruisfan/mongo-client:${MONGO_VERSION} bash
        ;;
    *)
        echo "error: No such command"
        printHelp
        exit 1;;
esac

